import { toggleNavigationBar } from "./UI/navigation/toggleNavigation";
import { addTask, completeTask, editTask } from "./AppLogic/task";
import { addProject, deleteProject, editProject } from "./AppLogic/project";
import { egg } from "./UI/modal/addTask";
import { mainProjects } from "./UI/navigation/switchProject";
import { joe } from "./UI/task/populateTasks";
import { john } from "./UI/modal/editTask";
import { egg2 } from "./UI/modal/addProject";
import { joem } from "./UI/projects/populateProjects";
import { testtt } from "./UI/modal/editProject";
